# Copyright 2022 Ubuntu
# See LICENSE file for licensing details.
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  external-hostname:
    default: ""
    description: |
      The external hostname this application should be available on. If unset,
      it will default to the deployed application name in the model.
    type: string
  disable-authentication:
    default: False
    description: |
      Flag to disable user management. If true, the user won't be prompted to
      register for an account.
    type: boolean
