name: Tests
on:
  pull_request:

jobs:
  ci-ignore:
    name: Check against ignorelist
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.diff.outputs.files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Expand ignorelist
        shell: bash
        run: |
          test -f .ciignore || wget https://raw.githubusercontent.com/canonical/observability/main/.ciignore
          while IFS= read -r globline; do
            compgen -G "$globline" >> .ciignore-expanded
          done < .ciignore
          mv .ciignore-expanded .ciignore
          sed -i '/^$/d' .ciignore
      - name: Generate diff
        id: diff
        shell: bash
        run: |
          base="remotes/origin/${{ github.base_ref }}"
          head="remotes/origin/${{ github.head_ref }}"
          echo "Comparing $base to $head"
          files=$(comm -23 <(git diff --name-only $base $head | sort) <(sort .ciignore))
          echo "$files"
          echo "files=$files" | tr -d '\n' >> $GITHUB_OUTPUT
  run-tests:
    name: Run Tests
    needs:
      - ci-ignore
    uses: ./.github/workflows/ci.yaml
