name: Tests
on:
  pull_request:

jobs:
  ci-ignore:
    name: Check against ignorelist
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.diff.outputs.files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Expand ignorelist
        shell: bash
        run: |
          echo "-- Check everything is there --"
          which wget
          which python
          which sed
          which test
          echo "----"
          echo "1. Testing file or running wget"
          test -f .ciignore || wget https://raw.githubusercontent.com/canonical/observability/main/.ciignore
          echo "2. Running while over file"
          while IFS= read -r globline; do
            echo "3. Executing python check for line $globline"
            python -c "from glob import glob; print(\"\n\".join(glob(\"$globline\")))" >> .ciignore-expanded
          done < .ciignore
          echo "4. Loop is finished, moving to .ciignore"
          mv .ciignore-expanded .ciignore
          echo "5. Executing sed to remove blank lines"
          sed -i '/^$/d' .ciignore
          echo "6. Finished!"
      - name: Generate diff
        id: diff
        shell: bash
        run: |
          base="remotes/origin/${{ github.base_ref }}"
          head="remotes/origin/${{ github.head_ref }}"
          echo "Comparing $base to $head"
          files=$(comm -23 <(git diff --name-only $base $head | sort) <(sort .ciignore))
          echo "$files"
          echo "files=$files" | tr -d '\n' >> $GITHUB_OUTPUT
  run-tests:
    name: Run Tests
    needs:
      - ci-ignore
    uses: ./.github/workflows/ci.yaml
